### ISSUE TITLE
matricázás

### ISSUE THREAD

**Issue by stantonavery** [2m2a4/2m2a4.github.io#19]
a szabályzatból való kivétel ellenére még mindig bent van a "max 10"-es limit 
el van írva a "játékosok a matricákból bárkinek adHATnak"
"vannak, akik...."-nál a vesszőnek az "akik" szó előtt van a helye
első bekezdésnél "azokat, melyekben" szavak között kell vessző

"Ha a terved vektoros formában tárolható és a mérete nem haladja meg a 256 kilobyte-ot, akkor el is juttathatod hozzánk és ha nekünk is tetszik felrakjuk a többi variáció közé." --- én ugyan értem ennek a mondatnak a lényegét, de nem vesz el kicsit a decentralizáltság-élményből az olvasóban? (főleg azért, mert szerintem ez a decentralizáltság érzés egyelőre nem része a mindennapi életnek, ezért ezt is ennek az oldalnak kell maradéktalanul megteremtenie). úgy érzem ez kicsit megteremt egy mi-te viszonyt, ami megbontja a teljesen egységes "mi" érzést. azt javaslom, hogy ehelyett legyen az, hogy "ha vektoros formában tárolható....akkor fel is töltheted", vagy "a honlapon is elérhetővé tudod tenni", vagy ilyesmi

**Comment by doktordroid** [comment]
Done. Thanks! :)
